// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getComicsByNums = `-- name: GetComicsByNums :many
SELECT month, num, link, year, news, safe_title, transcript, alt, img, title, day
FROM comics
WHERE num = ANY($1::INT[])
`

func (q *Queries) GetComicsByNums(ctx context.Context, nums []int32) ([]Comic, error) {
	rows, err := q.db.Query(ctx, getComicsByNums, nums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.Month,
			&i.Num,
			&i.Link,
			&i.Year,
			&i.News,
			&i.SafeTitle,
			&i.Transcript,
			&i.Alt,
			&i.Img,
			&i.Title,
			&i.Day,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComicsRange = `-- name: GetComicsRange :many
SELECT month, num, link, year, news, safe_title, transcript, alt, img, title, day
FROM comics
WHERE $1 <= num AND num <= $2
`

type GetComicsRangeParams struct {
	From pgtype.Int4 `json:"from"`
	To   pgtype.Int4 `json:"to"`
}

func (q *Queries) GetComicsRange(ctx context.Context, arg GetComicsRangeParams) ([]Comic, error) {
	rows, err := q.db.Query(ctx, getComicsRange, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comic{}
	for rows.Next() {
		var i Comic
		if err := rows.Scan(
			&i.Month,
			&i.Num,
			&i.Link,
			&i.Year,
			&i.News,
			&i.SafeTitle,
			&i.Transcript,
			&i.Alt,
			&i.Img,
			&i.Title,
			&i.Day,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestComic = `-- name: GetLatestComic :one
SELECT month, num, link, year, news, safe_title, transcript, alt, img, title, day
FROM comics
WHERE num = (SELECT MAX(num) FROM comics)
`

func (q *Queries) GetLatestComic(ctx context.Context) (Comic, error) {
	row := q.db.QueryRow(ctx, getLatestComic)
	var i Comic
	err := row.Scan(
		&i.Month,
		&i.Num,
		&i.Link,
		&i.Year,
		&i.News,
		&i.SafeTitle,
		&i.Transcript,
		&i.Alt,
		&i.Img,
		&i.Title,
		&i.Day,
	)
	return i, err
}

type InsertComicsParams struct {
	Month      pgtype.Text `json:"month"`
	Num        pgtype.Int4 `json:"num"`
	Link       pgtype.Text `json:"link"`
	Year       pgtype.Text `json:"year"`
	News       pgtype.Text `json:"news"`
	SafeTitle  pgtype.Text `json:"safe_title"`
	Transcript pgtype.Text `json:"transcript"`
	Alt        pgtype.Text `json:"alt"`
	Img        pgtype.Text `json:"img"`
	Title      pgtype.Text `json:"title"`
	Day        pgtype.Text `json:"day"`
}
