// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inverted_index.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFromInvertedIndex = `-- name: GetFromInvertedIndex :many
SELECT comics_nums
FROM inverted_index
WHERE word = ANY($1::TEXT[])
`

func (q *Queries) GetFromInvertedIndex(ctx context.Context, words []string) ([][]int32, error) {
	rows, err := q.db.Query(ctx, getFromInvertedIndex, words)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]int32{}
	for rows.Next() {
		var comics_nums []int32
		if err := rows.Scan(&comics_nums); err != nil {
			return nil, err
		}
		items = append(items, comics_nums)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertIntoInvertedIndexParams struct {
	Word       pgtype.Text `json:"word"`
	ComicsNums []int32     `json:"comics_nums"`
}
