// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comic struct {
	Month      pgtype.Text `json:"month"`
	Num        pgtype.Int4 `json:"num"`
	Link       pgtype.Text `json:"link"`
	Year       pgtype.Text `json:"year"`
	News       pgtype.Text `json:"news"`
	SafeTitle  pgtype.Text `json:"safe_title"`
	Transcript pgtype.Text `json:"transcript"`
	Alt        pgtype.Text `json:"alt"`
	Img        pgtype.Text `json:"img"`
	Title      pgtype.Text `json:"title"`
	Day        pgtype.Text `json:"day"`
}

type InvertedIndex struct {
	Word       pgtype.Text `json:"word"`
	ComicsNums []int32     `json:"comics_nums"`
}
