// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetComicsRange(ctx context.Context, arg GetComicsRangeParams) ([]Comic, error)
	GetLatestComicNum(ctx context.Context) (int32, error)
	InsertComics(ctx context.Context, arg []InsertComicsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
