// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetComicsByNums(ctx context.Context, nums []int32) ([]Comic, error)
	GetComicsRange(ctx context.Context, arg GetComicsRangeParams) ([]Comic, error)
	GetFromInvertedIndex(ctx context.Context, words []string) ([][]int32, error)
	GetLatestComicNum(ctx context.Context) (int32, error)
	InsertComics(ctx context.Context, arg []InsertComicsParams) (int64, error)
	InsertIntoInvertedIndex(ctx context.Context, arg []InsertIntoInvertedIndexParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
