// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT login, password, role
FROM users
WHERE login = $1
  AND password = $2
`

type GetUserParams struct {
	Login    pgtype.Text `json:"login"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.Login, arg.Password)
	var i User
	err := row.Scan(&i.Login, &i.Password, &i.Role)
	return i, err
}
